// ─── Core Schema ─────────────────────────────────────────────────────────────
// The .tk.json format — the single source of truth

export interface TestFile {
  version: string;
  name: string;
  description?: string;
  baseUrl?: string;
  variables?: Record<string, unknown>;
  tests: TestCase[];
  /** Which executor runs this module's tests. Defaults to 'web' when absent. */
  engine?: 'web' | 'mobile';
  mobileConfig?: MobileConfig;
}

export interface MobileConfig {
  platform: 'android' | 'ios';
  /** Device/emulator/simulator identifier (adb serial or iOS simulator UDID) */
  deviceId?: string;
  /** Path to a .apk/.app/.ipa to install before the session starts */
  appPath?: string;
  /** Android: package id of an already-installed app */
  appPackage?: string;
  /** Android: activity to launch (defaults to the package's launch activity) */
  appActivity?: string;
  /** iOS: bundle id of an already-installed app */
  bundleId?: string;
}

export interface TestCase {
  id: string;
  name: string;
  steps: TestStep[];
  disabled?: boolean;
  tags?: string[];
}

export interface TestStep {
  id: string;
  type: string;
  params: Record<string, unknown>;
  children?: TestStep[];
  skip?: boolean;
  description?: string;
  /** Selector alternatives generated by the recorder, ranked by confidence */
  selectorSuggestions?: { type: string; value: string; confidence: number }[];
  /** Overrides the step's default timeout (ms). Ignored by container steps (if/repeat/for_each/try_catch). */
  timeout?: number;
  /** Additional attempts on failure before the step is marked failed. Ignored by container steps. */
  retry?: number;
}

// ─── Block System ────────────────────────────────────────────────────────────

export interface BlockDefinition {
  type: string;
  category: BlockCategory;
  label: string;
  description?: string;
  color: string;
  inputs: BlockInput[];
  hasChildren?: boolean; // For container blocks (if, repeat, etc.)
  execute: (params: Record<string, unknown>, ctx: ExecutionContext) => Promise<StepResult>;
}

export type BlockCategory = 'navigation' | 'interaction' | 'assertion' | 'api' | 'logic' | 'data' | 'mobile';

export interface BlockInput {
  name: string;
  label: string;
  type: 'text' | 'number' | 'dropdown' | 'checkbox' | 'code';
  required?: boolean;
  default?: unknown;
  placeholder?: string;
  options?: Array<{ label: string; value: string }>; // For dropdowns
}

// ─── Execution ───────────────────────────────────────────────────────────────

export interface ExecutionContext {
  variables: Map<string, unknown>;
  page: unknown;       // Playwright Page
  browser: unknown;    // Playwright Browser
  baseUrl?: string;
  log: (msg: string) => void;
}

export interface StepResult {
  stepId: string;
  type: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number;
  error?: string;
  output?: unknown;
}

export interface TestResult {
  testId: string;
  testName: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number;
  steps: StepResult[];
  error?: string;
}

export interface RunResult {
  file: string;
  results: TestResult[];
  summary: { total: number; passed: number; failed: number; skipped: number; duration: number };
}

// ─── Modular Project Structure ───────────────────────────────────────────────

export interface Environment {
  id: string;
  name: string;
  variables: Record<string, string>;
}

export interface AppManifest {
  version: string;
  name: string;
  description?: string;
  baseUrl?: string;
  variables?: Record<string, unknown>;
  modules: ModuleRef[];
}

export interface ModuleRef {
  id: string;
  folder: string; // relative path to .tk.module/ directory
}

export interface ModuleFile {
  id: string;
  name: string;
  description?: string;
  baseUrl?: string; // overrides app-level baseUrl
  order: number;
  tests: TestCase[];
  /** Which executor runs this module's tests. Defaults to 'web' when absent. */
  engine?: 'web' | 'mobile';
  mobileConfig?: MobileConfig;
}
